services:
  - type: web
    name: youtube-downloader-api
    env: node
    buildCommand: |
      curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /opt/render/project/src/yt-dlp
      chmod a+rx /opt/render/project/src/yt-dlp
      export PATH="/opt/render/project/src:$PATH"
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
